### ISSUE TITLE
Heavy CPU use causing hanging

### ISSUE THREAD

**Issue by LeandroMarceddu** [ekzhang/rpt#6]
Hello there.
 
I'm quite new to Rust but I wanted to use this lib to generate thumbnails for STLs in a neat way.
I have pretty much copy pasted the cylinder example and tried feeding it the paths to the STL, however this causes it to 'hang' and consume a lot of CPU, it also never finishes. Code snippet below.

I'm just wondering if this is the natural state of this library, seeing it is 'cpu' only.

```
pub fn gen_thumb(path: PathBuf) -> color_eyre::Result<()> {
    use std::fs::File;
    color_eyre::install()?;
    let mut extension = path.clone();
    extension.set_extension("png");
    
    let mut scene = Scene::new();
    scene.add(
        Object::new(load_stl(File::open(path)?)?)
            .material(Material::specular(hex_color(0xB7CA79), 0.1))
    );
        scene.add(
        Object::new(plane(glm::vec3(0.0, 1.0, 0.0), -1.0))
            .material(Material::diffuse(hex_color(0xAAAAAA))),
    );
    scene.add(Light::Ambient(glm::vec3(0.01, 0.01, 0.01)));
    scene.add(Light::Object(
        Object::new(
            sphere()
                .scale(&glm::vec3(2.0, 2.0, 2.0))
                .translate(&glm::vec3(0.0, 20.0, 3.0)),
        )
        .material(Material::light(glm::vec3(1.0, 1.0, 1.0), 160.0)),
    ));
    scene.add(Light::Object(
        Object::new(
            sphere()
                .scale(&glm::vec3(0.05, 0.05, 0.05))
                .translate(&glm::vec3(-1.0, 0.71, 0.0)),
        )
        .material(Material::light(hex_color(0xFFAAAA), 400.0)),
    ));

    let camera = Camera::look_at(
        glm::vec3(-2.5, 4.0, 6.5),
        glm::vec3(0.0, 0.0, 0.0),
        glm::vec3(0.0, 1.0, 0.0),
        std::f64::consts::FRAC_PI_6,
    );
    Renderer::new(&scene, camera)
        .max_bounces(2)
        .num_samples(1)
        .render()
        .save(extension.as_path())?;

    Ok(())
}
```

**Comment by ekzhang** [comment]
Can you try compiling with optimizations turned on? The cylinder example should be fairly quick, since it only takes 1 sample. Either add run with `--release` or add this to your Cargo.toml:

```toml
[profile.dev]
opt-level = 2
```

**Comment by LeandroMarceddu** [comment]
Aha, thanks for this. Adding the profile.dev section resulted in an error this time, instead of just hanging. Appended below. Sadly this tells me nothing, but it might tell you something.

```
[31mThe application panicked (crashed).[0m
Message:  [36mcould not set the provided `Theme` via `color_spantrace::set_theme` globally as another was already set: InstallThemeError[0m
Location: [35mC:\Users\leand\.cargo\registry\src\github.com-1ecc6299db9ec823\color-eyre-0.5.11\src\config.rs[0m:[35m736[0m

  â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”� BACKTRACE â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�
  [96m                              â‹® 13 frames hidden â‹®                              [0m
  14: [32mcore::result::Result<T,E>::expect[0m[90m::h743b1205f56c1877[0m
      at [35m/rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\library\core\src/result.rs[0m:[35m1022[0m
  [96m                              â‹® 3 frames hidden â‹®                               [0m
  18: [91mplaterflow::processes::gen_thumb[0m[90m::ha1900fff45d67346[0m
      at [35mD:\Projects\PlaterFlow\src\processes.rs[0m:[35m159[0m
  19: [91mplaterflow::processes::plater::run[0m[90m::h92ba25d708f86cc6[0m
      at [35mD:\Projects\PlaterFlow\src\processes.rs[0m:[35m149[0m
  20: [91mplaterflow::main[0m[90m::h29ff971bb18bb419[0m
      at [35mD:\Projects\PlaterFlow\src\main.rs[0m:[35m34[0m
  21: [32mcore::ops::function::FnOnce::call_once[0m[90m::h77012c5fd1eb9014[0m
      at [35m/rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\library\core\src\ops/function.rs[0m:[35m227[0m
  [96m                              â‹® 14 frames hidden â‹®                              [0m

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
```

**Comment by ekzhang** [comment]
It looks like you're calling `color_eyre::install()` twice, could you fix that?

**Comment by LeandroMarceddu** [comment]
> It looks like you're calling `color_eyre::install()` twice, could you fix that?

I'll be damned. That did it; at least this time it outputs something although nothing even remotely close to the STLs, but progress is progress. The first generates an image of a starry sky for some reason, the second is just black. If I want to batch generate several STLs, what is the best way to clear everything? As I have a feeling this is happening with the second STL. (added both STLs and generated images [here](https://github.com/ekzhang/rpt/files/8693715/1.zip))

**Comment by LeandroMarceddu** [comment]
Figured it mostly out, taking a crash course on 3D Vectors right now to get everything set up properly. Thanks; I'll close this.

**Comment by ekzhang** [comment]
No worries! Glad you figured it out. If you're generating thumbnails within an application on demand, then you may want to try out a faster rendering algorithm, since path tracing is mostly used for ahead-of-time renders because it's so expensive.

Some links that might be useful: https://arewegameyet.rs/ecosystem/3drendering/ and https://github.com/asny/three-d

**Comment by LeandroMarceddu** [comment]
Yes, it seems like things such as kiss3d are perhaps more up to the task..
Never thought just generating thumbnails of an STL would be such an
endeavour in Rust, haha.

Thanks for all the help.

**Comment by ekzhang** [comment]
3D graphics isn't easy!
